version: '3'

services:
  wp:
    container_name: wordpress
    build:
      dockerfile: ${PWD}/dockerfiles/wordpress/Dockerfile
      context: ${PWD}
    volumes:
      - wp_app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
    links:
      - db
    restart: always

  db:
    image: mysql:5.7
    container_name: mysql_57
    ports:
      - ${IP}:3306:3306
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ${PWD}/data/mysql-dump:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    restart: always

  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: nginx
    ports:
      - '8000:8000'
    volumes:
      - ${PWD}/data/nginx/conf.d/:/etc/nginx/conf.d
      - wp_app:/var/www/html
#      - ${PWD}/ephemeral/logs/nginx:/var/log/nginx
    depends_on:
      - wp
    restart: always

  pinger:
    container_name: pinger
    build:
      dockerfile: ${PWD}/dockerfiles/pinger/Dockerfile
      context: ${PWD}
    tty: true
    depends_on:
      - nginx
    restart: always

volumes:
  db_data: {}
  wp_app: {}
